apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  labels:
    app: fcr
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcr
      type: celery-pod
  template:
    metadata:
      labels:
        app: fcr
        type: celery-pod
    spec:
      containers:
        - name: celery
          image: fastapi-celery-flower
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"          
          command: ["celery"]
          args: ["-A", "celery_worker.celery", "worker", "--loglevel=info"]
          