apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
  labels:
    app: fcr
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcr
      type: flower-pod
  template:
    metadata:
      labels:
        app: fcr
        type: flower-pod
    spec:
      containers:
        - name: flower
          image: fastapi-celery-flower
          imagePullPolicy: Never
          ports:
            - containerPort: 5555
          env:
              - name: FLOWER_PORT
                value: "5555"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"          
          command: ["celery"]
          args: ["-A", "celery_worker.celery", "flower", "--broker:amqp://guest:guest@rabbitmq:5672//"]