apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: fcr
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcr
      type: rabbitmq-pod
  template:
    metadata:
      labels:
        app: fcr
        type: rabbitmq-pod
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.8-alpine
          imagePullPolicy: Never
          ports:
            - containerPort: 4369
            - containerPort: 5671
            - containerPort: 5672      
          resources:
          # allocate more resources for rabbitmq, crash otherwise
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"                    