kind: Service 
apiVersion: v1 
metadata:
  name: rabbitmq
  labels:
    app: fcr
    type: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: fcr
    type: rabbitmq-pod
  ports:
    - port: 5672 
      targetPort: 5672